#!/bin/bash
sudo apt-get install -y python3-lxml
sudo pip3 install flask_cors # if it was not installed yet
sudo pip3 install flasgger
#If the RestAPI is not starting, please read the error message. Based on the(ses) error message(s), you will have to troubleshoot potential dependencies issues.

##Here some solutions:

#jsonschema exception
sudo pip3 uninstall -y jsonschema 
sudo pip3 install jsonschema==3.0.1

sudo pip3 install pathlib2

# I expose the port 5001 of my vm to the port 5001 on my computer
config.vm.network :forwarded_port, guest: 5001, host: 5001 
